
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # Para ngnix unprivileged
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    client_body_temp_path /tmp/client_body;
    fastcgi_temp_path /tmp/fastcgi_temp;
    proxy_temp_path /tmp/proxy_temp;
    scgi_temp_path /tmp/scgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;

    upstream backend_ventas_local {
        server backend-ventas:8081;
    }
    upstream backend_ventas_prod {
        server backend-ventas:8081;
    }

    upstream backend_despachos_local {
        server backend-despachos:8084;
    }
    upstream backend_despachos_prod {
        server backend-despachos:8082;
    }

    resolver 127.0.0.11 ipv6=off valid=30s;

    map ${ENTORNO} $target_ventas {
        local   "backend_ventas_local";
        prod    "backend_ventas_prod";
        default "backend_ventas_prod";
    }

    map ${ENTORNO} $target_despachos {
        local   "backend_despachos_local";
        prod    "backend_despachos_prod";
        default "backend_despachos_prod";
    }

    server {
        listen 8083;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/v1/ventas {
            proxy_pass http://$target_ventas;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/despachos {
            proxy_pass http://$target_despachos;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}