apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-despacho
  labels:
    app: frontend-despacho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-despacho
  template:
    metadata:
      labels:
        app: frontend-despacho
    spec:
      containers:
        - name: frontend-despacho
          image: imagen-frontend
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-despacho
spec:
  selector:
    app: frontend-despacho
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30080
  type: LoadBalancer