apiVersion: v1
kind: Secret
metadata:
  name: innovatech-db-secrets
type: Opaque
stringData:
  mysql-root-password: "root"
  db-name: "innovatech_db"
  db-user: "innovatech_user"
  db-pass: "innovatech_pass"